Find replace shortcuts
zed-industries/zed pull request #10297
Opened 2024-04-08 20:43 UTC by alygin

This PR changes ways the Find/Replace functionality in the Buffer/Project Search is accessible via shortcuts. It makes those panels work the same way as in VS Code and Sublime Text.

The details are described in the issue: [Make Find/Replace easier to use](#9142)

There's a difficulty with Linux keybindings.

VS Code uses on MacOS:

| Action | Buffer Search | Project Search |
| --- | --- | --- |
| Find | `cmd-f` | `cmd-shift-f` |
| Replace | `cmd-alt-f` | `cmd-shift-h` |

VS Code uses on Linux:

| Action | Buffer Search | Project Search |
| --- | --- | --- |
| Find | `ctrl-f` | `ctrl-shift-f` |
| Replace | `ctrl-h` ❗ | `ctrl-shift-h` |

The problem is that `ctrl-h` is already taken by the `editor::Backspace` action in Zed on Linux.

There's two options here:

1. Change keybinding for `editor::Backspace` on Linux to something else, and use `ctrl-h` for the "replace in buffer" action.
2. Use some other keybinding on Linux in Zed. This PR introduces `ctrl-r` for this purpose, though I'm not sure it's the best choice. 

What do you think?

fixes #9142

Release Notes:

- Improved access to "Find/Replace in Buffer" and "Find/Replace in Files" via shortcuts (#9142).

Optionally, include screenshots / media showcasing your addition that can be included in the release notes.

- N/A

2024-04-08 21:36 UTC, mikayla-maki requested changes

2024-04-08 21:36 UTC, mikayla-maki commented on assets/keymaps/default-linux.json
> +      "ctrl-r": "search::ToggleReplace"
Let's change this to ctrl-h

2024-04-09 04:04 UTC, alygin commented
> We should remove the `ctrl-h` binding to backspace on Linux.

What about `ctrl-h` binding to `zed::Hide` on Linux? This is a binding in the global context, so it has no direct conflict with Find/Replace in buffer, yet it fires when there's no open editor. For instance, when the project panel is activated and the user hits `ctrl-h`. It's quite confusing.

I see the _"// todo(linux): Review the editor bindings"_ comment, so these bindings are probably not set in stone. I found that Ubuntu uses `alt-f9` to minimize the current window, but I'm not sure about other distros and if there's a consensus on this in Linux.

I'll comment this binding. If someone has an idea on what it should be, let's change it.

2024-04-09 04:06 UTC, alygin commented on assets/keymaps/default-linux.json
> +      "ctrl-r": "search::ToggleReplace"
Done.

2024-04-09 04:18 UTC, mikayla-maki commented
I say just change it to alt-f9 and let’s fix forward if someone files an issue :D

2024-04-09 04:27 UTC, alygin commented
> I say just change it to alt-f9 and let’s fix forward if someone files an issue :D

OK :)
Done

2024-04-09 05:06 UTC, mikayla-maki approved these changes

2024-04-09 05:07 UTC, merged