linux: Primary clipboard
zed-industries/zed pull request #10534
Opened 2024-04-14 22:43 UTC by apricotbucket28

Implements copying from and pasting to the primary selection.

Pasting from the primary selection has no issues. However, when copying to it:

- Haven't tested performance
- Unable to try with multibuffers right now (it crashes, even on master)
- I don't like the code

Release Notes:

- N/A

2024-04-16 23:10 UTC, apricotbucket28 commented
Looks like the terminal also needs its own implementation

2024-04-18 21:41 UTC, mikayla-maki requested changes

2024-04-18 21:41 UTC, mikayla-maki commented on crates/terminal/src/terminal.rs
> +                if let Some(selection_text) = term.selection_to_string() {
Can we hide these under a `cfg(linux)`?

2024-04-18 21:41 UTC, mikayla-maki commented
Looks great! Thank you for implementing this :D

2024-04-18 21:52 UTC, mikayla-maki approved these changes

2024-04-18 21:54 UTC, merged