Fix project-panel double click file support on Windows. #10898
zed-industries/zed pull request #10917
Opened 2024-04-24 02:26 UTC by huacnlee

Release Notes:

- Fixed project panel double click to force open file on Windows.

Ref issue: #10898 

@bennetbo 

I saw you was also used `event.down.click_count` in Markdown Preview.

https://github.com/zed-industries/zed/commit/7dccbd8e3b61c48ae174807a4023332b7c1df06a#diff-c8d1735cb347ea08d03198df112343ec50a74de8d50414a6f3be6c6d674c6d19R161

And this also used in other place:

<img width="870" alt="image" src="https://github.com/zed-industries/zed/assets/5518/b844e700-b95f-4cd2-987f-9e4305ebdd7c">

## Test demo after updated

Looks like it is no side effect

![2024-04-24 10 17 45](https://github.com/zed-industries/zed/assets/5518/0df4cf06-7448-4014-9df2-f2608a5f5314)

2024-04-24 20:04 UTC, mikayla-maki requested changes
This seems like a bug in our windows platform implementation, rather than a bug in our application. This fix only patches over the underlying problem.

2024-04-24 21:01 UTC, huacnlee commented
I have take a look for the mouse click implementation on Windows.

It is looks like we forgot to change MouseUp click_count in PR #9642. In that PR changes, I just saw only have MouseDown?

https://github.com/zed-industries/zed/blob/53f67a82414fa0429fe8f8bdc2098700f65aa4b6/crates/gpui/src/platform/windows/window.rs#L709

2024-04-24 23:30 UTC, mikayla-maki commented
That sounds like the problem then!

2024-04-25 00:34 UTC, huacnlee commented
@mikayla-maki You can review again now.

https://github.com/zed-industries/zed/assets/5518/cd6f4578-807b-4791-98c5-bc30175eeeb3

2024-04-25 17:01 UTC, mikayla-maki commented
Perfect!

2024-04-25 17:01 UTC, mikayla-maki approved these changes

2024-04-25 17:01 UTC, merged