x11: add XIM support
zed-industries/zed pull request #11657
Opened 2024-05-10 14:33 UTC by npmania

This pull request adds XIM (X Input Method) support to x11 platform.

The implementation utilizes xim-rs, a XIM library written entirely in Rust, to provide asynchronous XIM communication.
Preedit and candidate positioning are fully supported in the editor interface, yet notably absent in the terminal environment.

This work is sponsored by [Rainlab Inc.](https://rainlab.co.jp/en/)

2024-05-10 14:35 UTC, npmania commented
@cla-bot check

2024-05-10 15:43 UTC, npmania commented
https://github.com/zed-industries/zed/assets/113083996/c677619a-2d57-4867-bbe4-519e91b2ba34

Here's a short video testing English, BQN, Korean, Japanese and Chinese input.

2024-05-13 19:39 UTC, mikayla-maki commented
Thank you for this work, it's been needed!

Can you tell me a bit more about xim-rs? Is there a compelling reason to use it, rather than handling the xim messages ourselves?

2024-05-13 19:54 UTC, mikayla-maki requested changes

2024-05-13 22:55 UTC, npmania commented on crates/gpui/src/platform/linux/x11/window.rs
> +        if let Some(ref mut fun) = self.callbacks.borrow_mut().input {
When this behavior gets removed, Zed panics on input_handler.replace_and_mark_text_in_range() call while in vim_mode.

2024-05-13 23:00 UTC, npmania commented
> Can you tell me a bit more about xim-rs? Is there a compelling reason to use it, rather than handling the xim messages ourselves?

The XIM protocol is not implemented in XCB, so communicating with XIM with the current xcb_ffi would require manual parsing of the XIM protocol. xim-rs provides an XIM protocol parsing interface over x11rb client, allowing non-blocking communication with the XIM server.

2024-05-13 23:05 UTC, npmania commented on crates/gpui/src/platform/linux/x11/window.rs
> +                Some(0..text.chars().count()),
Could you please provide further details? The `text` variable here has UTF-8 data converted from [compound_text_to_utf8](https://github.com/npmania/xim-rs/blob/27132caffc5b9bc9c432ca4afad184ab6e7c16af/xim-ctext/src/lib.rs#L122) from function.

2024-05-14 17:03 UTC, mikayla-maki commented on crates/gpui/src/platform/linux/x11/window.rs
> +                Some(0..text.chars().count()),
Yes, the text variable is ok. The problem is the `replace_and_mark_text_in_range` function expects UTF-16, according to the name of the argument: (`new_selected_range_utf16`). This is ok on macOS and Windows, which provide UTF-16 data on their own, but in this code path we need to either:

1) Change downstream code to accept either UTF-8 or UTF-16 
2) Change this code to produce UTF-16. 

Saying that, I think I've changed my mind from my previous comment, and I think producing UTF-16 here might be a smaller change.

2024-05-14 17:37 UTC, mikayla-maki commented
Gotcha thanks for the context! I did some reading and research on XIM and have a better understanding of how this all fits together now :D

2024-05-14 17:42 UTC, mikayla-maki commented on crates/gpui/src/platform/linux/x11/window.rs
> +        if let Some(ref mut fun) = self.callbacks.borrow_mut().input {
IIRC on macOS, the way Zed behaves is:
- Get a keyboard event
- Send the keyboard event through the IME
- Send out the keyboard event (perhaps with IME data associated)
- Call the correct input handler method

So, it seems like the code is relying on that dispatch pattern, if you're getting that panic. We should try to replicate it if we can, let me go check.

2024-05-14 18:20 UTC, mikayla-maki requested changes

2024-05-14 18:21 UTC, mikayla-maki commented
See handle_key_event on macOS for a rough guide on how IME and keyevents should interact.

https://github.com/zed-industries/zed/blob/main/crates/gpui/src/platform/mac/window.rs#L1202-L1307

2024-05-14 20:10 UTC, apricotbucket28 commented on crates/gpui/src/platform/linux/x11/window.rs
> +                Some(0..text.chars().count()),
I'm not actually sure if we need to set the selection. I don't rely on IME myself but looking at videos from other people it seems like preedit text isn't selected. GTK and Zed underline preedit text anyway.

Screenshot from GTK:
![image](https://github.com/zed-industries/zed/assets/71973804/9a48ae1a-32fe-4ef0-81ee-c191c0ef5e68)


Refs:
https://github.com/zed-industries/zed/pull/11712#discussion_r1597727276
https://github.com/zed-industries/zed/pull/7488

2024-05-14 21:06 UTC, mikayla-maki commented on crates/gpui/src/platform/linux/x11/window.rs
> +                Some(0..text.chars().count()),
If we don't need it, we can just set None here. I just don't want us to be doing something that's explicitly wrong, but the exact details of what's right can be different.

2024-05-15 15:46 UTC, npmania commented on crates/gpui/src/platform/linux/x11/client.rs
> +        let ximc = match X11rbClient::init(Rc::clone(&xcb_connection), x_root_index, None) {
Thank you for the detailed review, modified as your suggestion on commit [29e2db5](https://github.com/zed-industries/zed/pull/11657/commits/29e2db5c55e2b8c2315328af4d26c54b48425ce2).

2024-05-16 18:37 UTC, mikayla-maki approved these changes

2024-05-16 18:38 UTC, mikayla-maki commented on crates/gpui/src/platform/linux/x11/window.rs
> +        if let Some(ref mut fun) = self.callbacks.borrow_mut().input {
Discussed this in discord, not possible with how much time XIM takes to process, and the results here are good enough.

2024-05-16 18:39 UTC, mikayla-maki commented on crates/gpui/src/platform/linux/x11/client.rs
> +                            if xim_connected {
Discussed this in discord, not possible with how much time XIM takes to process, and the results here are good enough.

2024-05-16 18:43 UTC, mikayla-maki commented
Seems that this PR needs a cargo fmt

2024-05-16 19:13 UTC, npmania commented
Oops, fixed formatting on the last commit. I believe I've ran typo checker and clippy already, so hopefully the rest will be fine.

2024-05-16 22:13 UTC, merged

2024-05-17 12:49 UTC, aohanhongzhi commented
![image](https://github.com/zed-industries/zed/assets/37319319/3db2bc6b-de9b-4f65-b114-4d3d5f2011bf)

2024-05-18 04:14 UTC, npmania commented
@aohanhongzhi Please provide me about your setup so I can reproduce it on my environment.
Maybe a new issue can be fine, titled something like "incorrect candidate window positioning on (Your setup)". You can tag my id there.

2024-05-19 04:32 UTC, eatradish commented
> @aohanhongzhi Please provide me about your setup so I can reproduce it on my environment. Maybe a new issue can be fine, titled something like "incorrect candidate window positioning on (Your setup)". You can tag my id there.

I was able to reproduce that this is the f`citx5-diagnose` output:

```
# 系统信息:
1.  `uname -a`:

        Linux Daylily 6.9.0-aosc-main #1 SMP PREEMPT_DYNAMIC Mon Apr  8 14:34:55 UTC 2024 x86_64 GNU/Linux

2.  `lsb_release -a`:

        LSB Version:	n/a
        Distributor ID:	AOSC OS
        Description:	AOSC OS
        Release:	11.4.1
        Codename:	Koshki

3.  `lsb_release -d`:

        Description:	AOSC OS

4.  `/etc/lsb-release`:

        # FSG lsb_release configuration file template
        # If the distribution is LSB compliant, uncomment the following line
        # and set the version appropriately
        # LSB_VERSION=""
        DISTRIB_ID="AOSC OS"
        DISTRIB_CODENAME="Koshki"
        DISTRIB_RELEASE="11.4.1"
        DISTRIB_DESCRIPTION="AOSC OS"

5.  `/etc/os-release`:

        PRETTY_NAME="AOSC OS (11.4.1)"
        NAME="AOSC OS"
        VERSION_ID="11.4.1"
        VERSION="11.4.1 (Koshki)"
        BUILD_ID="20240507"
        ID=aosc
        ANSI_COLOR="1;36"
        HOME_URL="https://aosc.io/"
        SUPPORT_URL="https://github.com/AOSC-Dev/aosc-os-abbs"
        BUG_REPORT_URL="https://github.com/AOSC-Dev/aosc-os-abbs/issues/new/choose"

6.  桌面环境：

    桌面环境为 `kde`。

7.  XDG 会话类型：

        XDG_SESSION_TYPE='x11'

8.  Bash 版本：

        BASH_VERSION='5.2.26(1)-release'

# 环境：
1.  DISPLAY:

        DISPLAY=':0'


        WAYLAND_DISPLAY=''

2.  键盘布局：

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc104)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc104", "us", "", ""

3.  Locale：

    1.  全部可用 locale：

            aa_DJ
            aa_DJ.iso88591
            aa_DJ.utf8
            aa_ER
            aa_ER@saaho
            aa_ER.utf8
            aa_ER.utf8@saaho
            aa_ET
            aa_ET.utf8
            af_ZA
            af_ZA.iso88591
            af_ZA.utf8
            agr_PE
            agr_PE.utf8
            ak_GH
            ak_GH.utf8
            am_ET
            am_ET.utf8
            an_ES
            an_ES.iso885915
            an_ES.utf8
            anp_IN
            anp_IN.utf8
            ar_AE
            ar_AE.iso88596
            ar_AE.utf8
            ar_BH
            ar_BH.iso88596
            ar_BH.utf8
            ar_DZ
            ar_DZ.iso88596
            ar_DZ.utf8
            ar_EG
            ar_EG.iso88596
            ar_EG.utf8
            ar_IN
            ar_IN.utf8
            ar_IQ
            ar_IQ.iso88596
            ar_IQ.utf8
            ar_JO
            ar_JO.iso88596
            ar_JO.utf8
            ar_KW
            ar_KW.iso88596
            ar_KW.utf8
            ar_LB
            ar_LB.iso88596
            ar_LB.utf8
            ar_LY
            ar_LY.iso88596
            ar_LY.utf8
            ar_MA
            ar_MA.iso88596
            ar_MA.utf8
            ar_OM
            ar_OM.iso88596
            ar_OM.utf8
            ar_QA
            ar_QA.iso88596
            ar_QA.utf8
            ar_SA
            ar_SA.iso88596
            ar_SA.utf8
            ar_SD
            ar_SD.iso88596
            ar_SD.utf8
            ar_SS
            ar_SS.utf8
            ar_SY
            ar_SY.iso88596
            ar_SY.utf8
            ar_TN
            ar_TN.iso88596
            ar_TN.utf8
            ar_YE
            ar_YE.iso88596
            ar_YE.utf8
            as_IN
            as_IN.utf8
            ast_ES
            ast_ES.iso885915
            ast_ES.utf8
            ayc_PE
            ayc_PE.utf8
            az_AZ
            az_AZ.utf8
            az_IR
            az_IR.utf8
            be_BY
            be_BY.cp1251
            be_BY@latin
            be_BY.utf8
            be_BY.utf8@latin
            bem_ZM
            bem_ZM.utf8
            ber_DZ
            ber_DZ.utf8
            ber_MA
            ber_MA.utf8
            bg_BG
            bg_BG.cp1251
            bg_BG.utf8
            bhb_IN.utf8
            bho_IN
            bho_IN.utf8
            bho_NP
            bho_NP.utf8
            bi_VU
            bi_VU.utf8
            bn_BD
            bn_BD.utf8
            bn_IN
            bn_IN.utf8
            bo_CN
            bo_CN.utf8
            bo_IN
            bo_IN.utf8
            bokmal
            br_FR
            br_FR@euro
            br_FR.iso88591
            br_FR.iso885915@euro
            br_FR.utf8
            brx_IN
            brx_IN.utf8
            bs_BA
            bs_BA.iso88592
            bs_BA.utf8
            byn_ER
            byn_ER.utf8
            C
            ca_AD
            ca_AD.iso885915
            ca_AD.utf8
            ca_ES
            ca_ES@euro
            ca_ES.iso88591
            ca_ES.iso885915@euro
            ca_ES.utf8
            ca_ES.utf8@valencia
            ca_ES@valencia
            ca_FR
            ca_FR.iso885915
            ca_FR.utf8
            ca_IT
            ca_IT.iso885915
            ca_IT.utf8
            catalan
            ce_RU
            ce_RU.utf8
            chr_US
            chr_US.utf8
            ckb_IQ
            ckb_IQ.utf8
            cmn_TW
            cmn_TW.utf8
            crh_UA
            crh_UA.utf8
            croatian
            csb_PL
            csb_PL.utf8
            cs_CZ
            cs_CZ.iso88592
            cs_CZ.utf8
            C.utf8
            cv_RU
            cv_RU.utf8
            cy_GB
            cy_GB.iso885914
            cy_GB.utf8
            czech
            da_DK
            da_DK.iso88591
            da_DK.utf8
            danish
            dansk
            de_AT
            de_AT@euro
            de_AT.iso88591
            de_AT.iso885915@euro
            de_AT.utf8
            de_BE
            de_BE@euro
            de_BE.iso88591
            de_BE.iso885915@euro
            de_BE.utf8
            de_CH
            de_CH.iso88591
            de_CH.utf8
            de_DE
            de_DE@euro
            de_DE.iso88591
            de_DE.iso885915@euro
            de_DE.utf8
            de_IT
            de_IT.iso88591
            de_IT.utf8
            de_LI.utf8
            de_LU
            de_LU@euro
            de_LU.iso88591
            de_LU.iso885915@euro
            de_LU.utf8
            deutsch
            doi_IN
            doi_IN.utf8
            dsb_DE
            dsb_DE.utf8
            dutch
            dv_MV
            dv_MV.utf8
            dz_BT
            dz_BT.utf8
            eesti
            el_CY
            el_CY.iso88597
            el_CY.utf8
            el_GR
            el_GR@euro
            el_GR.iso88597
            el_GR.iso88597@euro
            el_GR.utf8
            en_AG
            en_AG.utf8
            en_AU
            en_AU.iso88591
            en_AU.utf8
            en_BW
            en_BW.iso88591
            en_BW.utf8
            en_CA
            en_CA.iso88591
            en_CA.utf8
            en_DK
            en_DK.iso88591
            en_DK.utf8
            en_GB
            en_GB.iso88591
            en_GB.utf8
            en_HK
            en_HK.iso88591
            en_HK.utf8
            en_IE
            en_IE@euro
            en_IE.iso88591
            en_IE.iso885915@euro
            en_IE.utf8
            en_IL
            en_IL.utf8
            en_IN
            en_IN.utf8
            en_NG
            en_NG.utf8
            en_NZ
            en_NZ.iso88591
            en_NZ.utf8
            en_PH
            en_PH.iso88591
            en_PH.utf8
            en_SC.utf8
            en_SG
            en_SG.iso88591
             [...]

2024-05-19 08:10 UTC, npmania commented
@eatradish Thanks a lot! I will try to investigate into this issue in a few days.