fix: reveal_path blocks on linux
zed-industries/zed pull request #11702
Opened 2024-05-11 15:29 UTC by FlafyDev

If you go to the file tree and press "x" (which is "project_panel::RevealInFinder"). It will open the default file manager(in my case nautilus). But on Linux it makes Zed unresponsive. This fixes that.

Release Notes:

- Fixed Zed blocked after opening file manager in the file tree on Linux.

2024-05-11 15:31 UTC, FlafyDev commented
@cla-bot check

2024-05-11 16:12 UTC, apricotbucket28 requested changes
`that_in_background` spawns an additional thread, we should prefer `that_detached`.

Also, the call above should be replaced too.

2024-05-11 16:40 UTC, FlafyDev commented
> `that_in_background` spawns an additional thread, we should prefer `that_detached`.
> 
> Also, the call above should be replaced too.

done

2024-05-14 17:54 UTC, mikayla-maki commented
Thanks!

2024-05-14 18:18 UTC, merged