Update linux instruction for fedora missing openssl perl depencies
zed-industries/zed pull request #11868
Opened 2024-05-15 17:45 UTC by yodatak

see https://docs.rs/openssl/latest/openssl/

Release Notes:

- Add more packages for fedora compilation

2024-05-15 17:46 UTC, mikayla-maki requested changes

2024-05-15 17:46 UTC, mikayla-maki commented on script/linux
> +    # Perl dependcies are needed for openssl-sys crate see https://docs.rs/openssl/latest/openssl/
nit: dependcies -> dependencies

2024-05-17 06:33 UTC, yodatak commented on script/linux
> +    # Perl dependcies are needed for openssl-sys crate see https://docs.rs/openssl/latest/openssl/
Thanks and sorry 😅

2024-05-17 17:38 UTC, mikayla-maki approved these changes

2024-05-17 17:38 UTC, merged