editor: Add Cut, Copy and Paste actions to the context menu
zed-industries/zed pull request #11878
Opened 2024-05-15 21:48 UTC by vitallium

Hi, I saw someone on Twitter mentioned that missing Cut, Copy and Paste actions in the context menu in the editor block them from using Zed. It turns out that resolving this issue is simply a matter of adding these actions to the mouse context menu. To keep items in the context menu grouped, I placed them at the top of the menu with a separator at the end. Let me know if that's OK. Thanks!

Here is the screenshot:

![CleanShot 2024-05-15 at 23 45 46@2x](https://github.com/zed-industries/zed/assets/1894248/afd44f96-a6cd-4756-adbd-326224889f61)

Release Notes:

- Added "Cut", "Copy" and "Paste" actions to the context menu ([#4280](https://github.com/zed-industries/zed/issues/4280)).

2024-05-15 22:20 UTC, maxdeviant requested changes
Can we put this section after the separator following `Code Actions` and before `Reveal in Finder`?

2024-05-16 05:06 UTC, vitallium commented
@maxdeviant sure thing. I've updated this PR and the screenshot. Thanks.

2024-05-16 12:58 UTC, maxdeviant approved these changes
Thank you, looks good!

2024-05-16 12:59 UTC, merged

2024-05-17 04:08 UTC, 0x2CA commented
There seems to be a problem.

https://github.com/zed-industries/zed/assets/19868292/598f9cfb-caf8-4a9c-959b-ffd5c1586aba