Add runnable tasks to elixir
zed-industries/zed pull request #12526
Opened 2024-05-31 12:19 UTC by jotaviobiondo

Release Notes:

- Added runnable tasks to Elixir (for modules, `describe` and `test` blocks)

https://github.com/zed-industries/zed/assets/7737375/06f1b4cb-0364-4c30-982d-6dda3193b5d2

2024-05-31 12:20 UTC, jotaviobiondo commented
@cla-bot check

2024-05-31 12:49 UTC, osiewicz commented
Slight nit: could we rename all captures (except for `@run`) to start with the underscore? 
Captures without an underscore prefix are exposed as environmental variable in a task (with `ZED_CUSTOM_` prefix), which means that the user could retrieve full text of `elixir_test` capture by referencing `ZED_CUSTOM_elixir_test` env variable in their task, which I suppose is not desirable.

2024-05-31 12:49 UTC, osiewicz commented on extensions/elixir/languages/elixir/runnables.scm
> +    ) @elixir-test
```suggestion
    ) @_elixir-test
```

2024-05-31 12:50 UTC, osiewicz commented on extensions/elixir/languages/elixir/runnables.scm
> +    ) @elixir-module-test
```suggestion
            (call target: (identifier) @_keyword (#any-of? @_keyword "describe" "test"))
        )
    ) @_elixir-module-test
```

2024-05-31 12:50 UTC, osiewicz requested changes
Slight nit: could we rename all captures (except for `@run`) to start with the underscore? 
Captures without an underscore prefix are exposed as environmental variable in a task (with `ZED_CUSTOM_` prefix), which means that the user could retrieve full text of `elixir_test` capture by referencing `ZED_CUSTOM_elixir_test` env variable in their task, which I suppose is not desirable.

Other than that, this looks good to me!

2024-05-31 14:06 UTC, jotaviobiondo commented
Done @osiewicz!

Didn't know about this behavior of captures in Zed, but it's a very nice feature! :)

2024-05-31 14:24 UTC, osiewicz approved these changes
LGTM

2024-05-31 18:49 UTC, merged

2024-06-05 21:55 UTC, baldwindavid commented
Thanks for adding @jotaviobiondo ! Would be super cool if `describe` and `test` showed up in the outline (`outline::Toggle`) as well; especially if the outline panel in https://github.com/zed-industries/zed/pull/12637 eventually goes in.