svelte: Improve syntax highlighting (#10893)
zed-industries/zed pull request #12788
Opened 2024-06-07 18:38 UTC by soerenmeier

This PR fixes `<script context="module">` not being highlighted.  
It also adds support for scss.

Release Notes:

- Fixed svelte syntax highlighting in `context="module"` ([#10893](https://github.com/zed-industries/zed/issues/10893)).
- Added scss syntax highlighting in svelte

2024-07-04 07:22 UTC, mtorromeo requested changes

2024-07-04 07:22 UTC, mtorromeo commented on extensions/svelte/languages/svelte/injections.scm
> +; match script tags without a lang tag
```suggestion
; match style tags without a lang tag
```

2024-07-04 07:22 UTC, mtorromeo commented on extensions/svelte/languages/svelte/injections.scm
> +; match javascript
```suggestion
; match css
```

2024-07-04 07:22 UTC, mtorromeo commented on extensions/svelte/languages/svelte/injections.scm
> +; match typescript
```suggestion
; match scss
```

2024-07-04 21:24 UTC, soerenmeier commented on extensions/svelte/languages/svelte/injections.scm
> +; match script tags without a lang tag
Thanks, fixed them

2024-07-10 19:42 UTC, maxdeviant approved these changes
Thanks!

2024-07-10 19:42 UTC, merged