omnisharp: solve problem of omnisharp server failing to download
zed-industries/zed pull request #13367
Opened 2024-06-21 14:48 UTC by windoflake

Fix issue #9181: https://github.com/zed-industries/zed/issues/9181.

1. The root cause for the issue is that zed downloads the zip files and it used external command utility 'unzip' to extract to zip file. However, not all systems are equipped with it at default. So zed reports error like 'failed to start language server "OmniSharp": No such file or directory (os error 2)'. Once it fails, zed keep constantly downloading the zip file. 
2. The solution is to use async_zip crate to extract the downloaded language zip file instead of calling 'unzip' command. So for any systems without `unzip`, zed should be working fine with it.
3. This fix also checks the existent of the language file to be downloaded. If the language file already exists, it just extracts the files directly, without trying to download again and again, which is kind of annoying.

Release Notes:

- - Fixed [#9181](https://github.com/zed-industries/zed/issues/9181).

2024-06-21 14:54 UTC, maxdeviant requested changes
This looks like it’s touching non-zip code paths.

The tar and tar.gz paths should be left as-is.

2024-06-21 23:52 UTC, windoflake commented
@cla-bot check

2024-06-22 03:56 UTC, windoflake commented
> * ``
> * Make sure that the git commit email is configured in your GitHub account settings, see

That's right. I've updated the code accordingly. 
And there is no need to check whether the zip file is downloaded or not. The check logic should have been done in CsharpExtension::language_server_binary_path from csharp.cs.

2024-06-23 01:01 UTC, windoflake commented
> This looks like it’s touching non-zip code paths.
> 
> The tar and tar.gz paths should be left as-is.


@maxdeviant , That's right. I've updated the code accordingly.
And there is no need to check whether the zip file is downloaded or not. The check logic should have been done in CsharpExtension::language_server_binary_path from csharp.cs. So I just change the unzip code.

2024-06-24 12:24 UTC, windoflake reviewed
Sorry, I seem to overwrite my last push by a forcing push. 
This is actually the commit that I changed according to the review comments. @maxdeviant

2024-07-05 15:38 UTC, maxdeviant commented
Thanks for your help with this, @windoflake!

I'm going to close this one out in favor of https://github.com/zed-industries/zed/pull/13869, as there's an existing function we can use to extract the `.zip` file.

2024-07-05 15:38 UTC, closed without merging