Makes resize cursor stay while dragging (+a few format/typo fixes)
zed-industries/zed pull request #15585
Opened 2024-08-01 04:27 UTC by danielzsh

Release Notes:

- Resize cursor stays while dragging (it previously would switch back to a normal arrow cursor)

Before:
https://github.com/user-attachments/assets/e69fa5d5-fe95-4233-8d83-89b51b41060f

After:

https://github.com/user-attachments/assets/6a161eca-335f-4a3b-ba6b-58ac58d4174d

2024-08-01 04:28 UTC, danielzsh commented
Currently the cursor still switches back to arrow half the time and I'm not too sure why...

2024-08-01 06:43 UTC, JunkuiZhang commented
This PR might not be accepted by the Zed team, see #11596.

2024-08-29 02:45 UTC, mikayla-maki requested changes

2024-08-29 02:45 UTC, mikayla-maki commented on crates/gpui/src/window.rs
> +                self.window.mouse_down = true;
I don't think this solution is sufficient yet, as the mouse exiting the window, releasing, and then re-entering might cause this `mouse_down` state to desync from the real mouse state. Maybe set it on mouse move too? We might need other events, let me know what you find :)

2024-09-30 22:05 UTC, mikayla-maki commented
Since it's been a month since I requested changes to this, I'm going to close this PR for now. But we'd still like this bug fix :)

2024-09-30 22:05 UTC, closed without merging