ruby: Replace default tasks with a stub message
zed-industries/zed pull request #16752
Opened 2024-08-23 14:16 UTC by vitallium

The Ruby world has many testing frameworks:

- Minitest
- RSpec
- quickdraw
- tldr
- and many others.

Attempting to support all of them through a single `tasks.json` file is a challenging task and nearly impossible. All testing frameworks have different running options and commands. It's still possible to use tree-sitter queries to detect runnables in Ruby code but Zed lacks the ability to detect the testing framework in a project that can be used to detect the correct commands to run tests or runnables. The end user knows the correct command and it's wise to delegate creating the command to them. It would be a bit strange to leave the user without any guidance, so this commit adds example tasks for various Ruby testing frameworks.

Closes #12579

Here is the screenshot how it looks:

![CleanShot 2024-07-01 at 19 37 08@2x](https://github.com/zed-industries/zed/assets/1894248/e9659822-6c02-4afb-a0e4-e9966b9fb2f5)

Release Notes:

- N/A

2024-08-23 14:19 UTC, vitallium commented
"I will mark this PR as a draft while I wait for a review from @joeldrapper.

2024-08-27 14:08 UTC, joeldrapper approved these changes
Looks good to me.

2024-08-27 14:46 UTC, vitallium commented
> Looks good to me.

Thank you! This PR is ready then.

2024-08-29 05:06 UTC, mikayla-maki commented
Is there some collision in test patterns that make ruby test frameworks difficult to use? Because this looks like it's just removing information from the kinds of ruby test we can detect. Why not just add the tasks for each test framework?

2024-08-29 05:14 UTC, mikayla-maki requested changes
Is there some collision in test patterns that make ruby test frameworks difficult to use? Because this looks like it's just removing information from the kinds of ruby test we can detect. Why not just add the tasks for each test framework?

2024-08-29 09:53 UTC, joeldrapper commented
> Why not just add the tasks for each test framework?

Mainly because there are so many different ways you might run tests in Ruby. For example, if you use Minitest, depending on how your project is setup, you might need to run any of the following commands to run your tests.

```
bundle exec rake
bundle exec rake test
bundle exec rails test
bin/rails test
bin/test
bundle exec rake parallel:test
```

I think the goal of this change is to surface information on how you can configure your own local test running task which the Ruby extension for Zed can use.

2024-08-29 17:31 UTC, mikayla-maki commented
Ahhh, I see the problem now. Thanks for the explanation :)

2024-08-29 17:32 UTC, merged