cpp: Improve completion display
zed-industries/zed pull request #17346
Opened 2024-09-04 11:49 UTC by XDeme1

Closes #17270 

* All identifiers are now displayed first, making function pointers completions more readable.
* Functions and methods now display their parameters.
* Snippets provided by the LSP now have a description.

Release Notes:

- N/A

2024-09-04 13:44 UTC, maxdeviant requested changes
> * All identifiers are now displayed first, making function pointers completions more readable.

The intent is for the completions to mirror what a definition would look like in source code, so don't think we want to make this change.

2024-09-12 17:22 UTC, WeetHet commented
> > * All identifiers are now displayed first, making function pointers completions more readable.
> 
> The intent is for the completions to mirror what a definition would look like in source code, so don't think we want to make this change.

In my opinion, that doesn't matter much. Putting name first would make much more sense in most cases, as it allows you to actually see what you're choosing and not just a huge type of the completion (e.g. ranges completions suffer a log):

<img width="700" alt="Screenshot 2024-09-12 at 20 21 46" src="https://github.com/user-attachments/assets/07a3c2d5-4b47-4881-a950-ca5a92773e0e">

2024-09-13 09:35 UTC, WeetHet commented
Xcode:
<img width="448" alt="Screenshot 2024-09-13 at 12 35 01" src="https://github.com/user-attachments/assets/cfb422e7-86a7-4265-9044-9382fa9158f9">

Lapce:
<img width="695" alt="Screenshot 2024-09-13 at 12 33 46" src="https://github.com/user-attachments/assets/0e19cc8e-caff-4015-a073-ef539cf20647">

VSCode:
<img width="611" alt="Screenshot 2024-09-13 at 12 31 11" src="https://github.com/user-attachments/assets/01cc3bae-1969-4ec1-92aa-67e5b0d7744c">

Fleet:
<img width="539" alt="Screenshot 2024-09-13 at 12 27 56" src="https://github.com/user-attachments/assets/2fe6aba0-abe5-4b43-932b-889e827da6ab">

2025-01-07 16:17 UTC, maxdeviant commented
While I think there are some good changes in this PR, it would make review easier if they were separated out into separate PRs for each individual change.

In particular, the implementation for "Function pointers should now match their source code definition." seems like it does a lot of string manipulation that seems like it could be brittle.

2025-01-07 16:17 UTC, closed without merging