add hint/predictive theme stylings, remove color blending and fix multiple background renderings on assistant panel
zed-industries/zed pull request #17606
Opened 2024-09-09 17:27 UTC by AlbertMarashi

…

Closes https://github.com/zed-industries/zed/issues/17599
Closes https://github.com/zed-industries/zed/issues/17392

Release Notes:

- Fixed theme hint & predictive backgrounds not displaying in editor
- Fixed issue where assistant panel would have `editor.background` applied multiple times
- Removed color blending with colors to allow for alpha values within theme styles

2024-09-11 04:54 UTC, AurevoirXavier commented
I'm uncertain whether this will resolve the inconsistent behavior of `"tab_bar.background"`.

<img width="463" alt="image" src="https://github.com/user-attachments/assets/e9c40934-a224-4ac6-bc11-884bbc1e1c43">

<img width="236" alt="image" src="https://github.com/user-attachments/assets/688a3180-ae84-4c5b-abd0-afa62261b7fc">

2024-09-11 07:52 UTC, AlbertMarashi commented
@AurevoirXavier I am leaning on no, but could you describe the issue a little more? I may be able to figure out whether this is occurring and add a fix for it

2024-09-11 08:00 UTC, AurevoirXavier commented
> @AurevoirXavier I am leaning on no, but could you describe the issue a little more? I may be able to figure out whether this is occurring here too and add a fix for it

Could you try adjust `tab_bar.background` in your `experimental.theme_overrides`?

2024-09-11 08:23 UTC, AlbertMarashi commented
@AurevoirXavier

I believe this may be coming from your `"panel.background"` setting. Can you try to set it to a transparent value such as `#FFF0`

2024-09-11 08:25 UTC, AurevoirXavier commented
> @AurevoirXavier
> 
> I believe this may be coming from your `"panel.background"` setting. Can you try to set it to a transparent value such as `#FFF0`

Hi, `panel.background` only controls the background of the terminal's content, not its tab bar.

2024-09-14 01:02 UTC, iamnbutler commented
Hey! These changes sound great. Can you provide some before/after screenshots in your description?

2024-09-15 02:55 UTC, AlbertMarashi commented
> Hey! These changes sound great. Can you provide some before/after screenshots in your description?

Done. Please see above

2024-09-17 05:50 UTC, iamnbutler commented
Looks good to me! Feel free to merge whenever you are ready.

2024-09-17 06:23 UTC, AlbertMarashi commented
@iamnbutler I don't work at zed so no can do 😆

2024-09-17 17:51 UTC, AlbertMarashi commented
@iamnbutler We may want to hold off on this for a minute, because it appears that about half the existing themes have set their `predictive.background` colors to some arbitrary colors - presumably because many were copied and pasted, or forgotten about because this feature didn't exist.

<img width="386" alt="image" src="https://github.com/user-attachments/assets/c6925a3f-6546-46c2-8d49-6b52fd378a24">

<img width="400" alt="image" src="https://github.com/user-attachments/assets/eea3a2a8-446e-42c6-b0e4-46f6ca3dc7e1">

<img width="378" alt="image" src="https://github.com/user-attachments/assets/ea25d564-14e1-497a-a8c5-f05f1f5c6a34">

Most of the themes are okay, but perhaps in order to prevent users from being disturbed through this update, we should either

- set all the predictive/hint backgrounds in all themes to `#0000` for transparent (maintains the current styling for all users, since none of these values were being used anywhere before).
- Go through each built-in theme to decide a good `predictive.background` and `hint.background` color for each. (This is more opinionated, but i'm happy to do it)

2024-09-17 18:05 UTC, maxdeviant commented
@AlbertMarashi I think this may be easier to land if we split it up into separate PRs.

Right now it seems like we're combining 3 unrelated things in one PR.

2024-09-17 18:17 UTC, AlbertMarashi commented
@maxdeviant yeah, I think I got carried away with testing some local improvements, I'm not a git wiz so i'd prefer to get these all merged in one go so I don't have to go back and redo them as seperate PRs 😆 - but I'm happy to if it's necessary

Here are my thoughts:

- `Use hint/predictive background` - This can be ready to merge with effectively no risk, **_`if we`_** just set all of the built-in theme `predictive.background`s and `hint.background`s settings to `#0000` (transparent), and come back to setting those theme values in a seperate PR (these are already invisible/not displayed for all users currently)
- `remove foreground color blending` - I think this is ready to merge.
- `Fix multiple background renderings on assistant panel` - I also think this is ready to merge. This will affect no built-in themes as they are all using opaque background values

2024-09-17 20:22 UTC, maxdeviant commented on crates/assistant/src/assistant_panel.rs
> -            .bg(cx.theme().colors().editor_background)
Removing this color has a change on the appearance of the configuration view, which we don't want.

2024-09-17 20:23 UTC, maxdeviant requested changes
I think it would be good to evaluate these changes independently.

I already moved the hint and predictive background styles out into a separate PR (and thus realized that they're not ready for merge, as-is): https://github.com/zed-industries/zed/pull/17969

2024-10-02 14:16 UTC, maxdeviant commented
Closing this out so we can split them up into separate PRs.

2024-10-02 14:16 UTC, closed without merging