project_panel: Open rename file editor if pasted file was disambiguated
zed-industries/zed pull request #19975
Opened 2024-10-30 19:03 UTC by Zollerboy1

Closes #19974.

When a file is pasted in the project panel at a location where a file with that name already exists, the new file's name is disambiguated by appending " copy" at the end. This happens on the paste and the duplicate actions, as well as when Alt-dragging files.
With this PR, this will now open the file rename editor with the disambiguator pre-selected.

Open question:
With this PR's current implementation, this won't always work when pasting multiple files at once. In this case, the file rename editor only opens for the last pasted file, if that file was disambiguated. If only other files were disambiguated instead, it won't open.
This roughly mimics the previous paste behaviour, namely that only the last pasted file was selected.

I see two options here: If multiple files were pasted and some of them were disambiguated, we could select and open the rename editor for the last file that was actually disambiguated (easy), or we could open a kind of multi-editor for all files (hard, but maybe a multi-rename editor could actually be interesting in general...).

Release Notes:

- Open rename file editor if pasted file was disambiguated

2024-12-13 02:16 UTC, mikayla-maki commented
Given the fact that this feature doesn't work with multi-selections, I don't think we want to attempt to use it. Lets special case this to only a single file paste operation.

2024-12-13 02:17 UTC, mikayla-maki requested changes
Given the fact that this feature doesn't work with multi-selections, I don't think we want to use it. Lets special case this behavior to only a single file paste operation.

2024-12-16 13:06 UTC, Zollerboy1 commented
@mikayla-maki that's a fair point. I've added a check if we're only pasting/alt-dragging a single file in the latest commit.

2024-12-16 13:19 UTC, Zollerboy1 commented
Question: should this be configurable in the `ProjectPanelSettings` (i.e. a bool that enables or disables this feature)?

2025-01-02 21:33 UTC, mikayla-maki approved these changes

2025-01-02 21:33 UTC, mikayla-maki commented
Thank you!

2025-01-02 22:06 UTC, merged