Port of `Align cursor` extension from vscode
zed-industries/zed pull request #20129
Opened 2024-11-03 07:34 UTC by sirynka

Inspired by: [align cursor](https://marketplace.visualstudio.com/items?itemName=yo1dog.cursor-align)

Ideally, I would have wanted to implement it as an actual extensions, instead of committing it into the core but have not figured how to do it yet. I'd be glad if you'd provide an example of how to interact with editor through the extension API.

2024-11-03 07:37 UTC, SomeoneToIgnore requested changes
This needs tests.

2024-11-03 07:38 UTC, SomeoneToIgnore commented
> I'd be glad if you'd provide an example of how to interact with editor through the extension API.

Nothing exists on that front, alas.

2024-11-03 09:13 UTC, sirynka commented
> This needs tests.

Is this enough: 849ffca8f2082ba73b6008c7b1658b8a1cbf0b99?

2024-11-03 09:21 UTC, SomeoneToIgnore commented
* to start with, read to the bot messages already

* Not sure how realistic my example is, but multiple ˇ on the same line seems like a good thing to check one way or another:

```py
while True:
        try:
ˇn = iˇnt(input("Enter the number of elements in the Fibonacci sequence: "))
    ˇif n <= 0:
                print("Please enter a positive integer greater than 0.")
                continue
            ˇbreak  # Exit the loop when a valid number is providedˇ
        except ValueError:
            print("Invalid input. Please enter an integer.")
```

2024-11-03 09:29 UTC, SomeoneToIgnore requested changes

2024-11-03 09:29 UTC, SomeoneToIgnore commented on crates/editor/src/editor.rs
> +                .map(|s| s.start.column)
What if we select backwards? Then `start` will be after the `end`.

2024-11-03 09:29 UTC, SomeoneToIgnore commented on crates/editor/src/editor.rs
> +                let spaces = " ".repeat((max_len - s.start.column) as usize);
The user may use tabs, is `" "` a good choice always?

2024-11-03 09:29 UTC, SomeoneToIgnore commented on crates/editor/src/editor.rs
> +                let spaces = " ".repeat((max_len - s.start.column) as usize);
Also same question as above, 

> What if we select backwards? Then `start` will be after the `end`.


In addition to that, does this all make sense when `max_len == 0`? 
Looks like a noop, and `0 - something` may actually panic, which is super bad.
This edge case needs a test.

2024-11-04 09:55 UTC, sirynka commented on crates/editor/src/editor.rs
> +            };
It could definitely be written in a smarter way.

2024-11-04 10:00 UTC, sirynka commented
> - to start with, read to the bot's messages already

I don't understand what else does `cla-bot` wants from me.
I have configured `user.email` to the same one that is set in my github profile
And unchecked **Keep my email addresses private** checkbox in profile settings.

2024-11-04 10:02 UTC, SomeoneToIgnore commented
The commits in this PR seem to be not updated: https://github.com/zed-industries/zed/pull/20129/commits
Have you updated the old commits' metadata?

2024-11-04 10:05 UTC, sirynka commented
@cla-bot check

2024-12-06 17:32 UTC, closed without merging