Add shortcuts for 'open settings' and 'revert selected hunks' to Jetbrains keymap
zed-industries/zed pull request #20414
Opened 2024-11-08 13:46 UTC by trin94

Closes #ISSUE

Release Notes:

- Added shortcuts for 'open settings' and 'revert selected hunks' to JetBrains keymap

2024-11-08 17:20 UTC, notpeter requested changes
Linux looks good. The two MacOS bindings are already in the default base keymap so don't need to be repeated in the jetbrains one. 

https://github.com/zed-industries/zed/blob/cd7416bfb452cf2b0abe9c9cc64f6b9103ed370d/assets/keymaps/default-macos.json#L127

https://github.com/zed-industries/zed/blob/cd7416bfb452cf2b0abe9c9cc64f6b9103ed370d/assets/keymaps/default-macos.json#L33

2024-11-08 17:31 UTC, trin94 commented
Undid the changes for the macOS layout :+1: 


> P.S. Next time if you make your changes on a branch of your fork (instead of on main) and check the box "Allow Maintainers to make changes" I could just commit the fix rather than requesting changes.

Alright, I didn't know that. Will do it next time :smiley:

2024-11-09 00:34 UTC, notpeter approved these changes

2024-11-09 00:34 UTC, merged

2024-11-09 00:34 UTC, notpeter commented
Thanks!