I've made the project panel respond to ui densitiy settings
zed-industries/zed pull request #20460
Opened 2024-11-09 15:58 UTC by Remco-Schoeman

I noticed a setting in the Zed config: `unstable.ui_density` while looking for ways to get more text on my cheap 1920x1080 second monitor. (I already had made the font 14px instead of the default 16px.)

While changing that setting to `compact` it did exactly what I wanted, I noticed the Project panel didn't play along. The panel didn't shrink the vertical whitespace between items which made it look a bit too 'airy'.

![zed-before-density](https://github.com/user-attachments/assets/29010821-5a3a-4f9f-91ba-78dd37e44051)

So, I fixed it.

![zed-after-density](https://github.com/user-attachments/assets/6f7c5911-0263-421b-9e6e-d1dd747dc195)

The diff seems large, but it's mostly whitespace because of the indentation changes.

The actual change is pretty small:

![zed-changeset](https://github.com/user-attachments/assets/113e31dc-2848-4dbd-bc79-3b956e74b596)

I've tried to see if and how I could add tests for this change, 
but I couldn't find an existing example for a test for a visual change like this.
Setting up such a test myself is beyond me as Rust is mostly arcane magic to me, so any assistance from somebody who does know is welcome.

2024-11-10 14:17 UTC, iamnbutler commented
Hey Remco! Thanks for working on expanding support for UI Density.

There is actually an even easier way to do this: 

Rather than even access the ui_density setting you can use [`ui::Spacing`](https://github.com/zed-industries/zed/blob/ebdc255b73b29bdf1b132a8d8fe19c0332164850/crates/ui/src/styles/spacing.rs#L13). It was built for this exact purpose, to allow defining spacing with density in mind.

So you could do something like this:

![CleanShot 2024-11-10 at 09 12 22@2x](https://github.com/user-attachments/assets/35e0aa5d-d6e6-41c4-baa2-918aacbd0fb1)

And it would automatically respond to density. ___However___ the scale I have set up in Spacing doesn't go high enough to account for this case. 

If you can give me a day or so to update the spacing scale in a separate PR, I'd prefer for us to use that approach as it keeps the way we build UI to respond to density consistent.

Alternatively, if you want to land this soon, you can use `Spacing::custom_spacing` for now and I can update it after I update the scale.

2024-11-10 14:18 UTC, iamnbutler requested changes

2024-11-10 14:18 UTC, iamnbutler commented on crates/project_panel/src/project_panel.rs
> +                                    theme::UiDensity::Comfortable => this.h_6(),
Let's use ui::Spacing rather than accessing the settings here!

2024-12-13 02:09 UTC, mikayla-maki commented
Hi @Remco-Schoeman , it seems whatever changes where in this PR got blown away by the merge. I'm going to set this to draft, feel free to mark it ready for review once this PR is back in shape :)

2025-01-06 13:38 UTC, iamnbutler commented
As this hasn't received an update in over a month I'm going to close it out for now. Feel free to re-open and assign me if you come back to it @Remco-Schoeman.

2025-01-06 13:38 UTC, closed without merging