Enable clangd's dot-to-arrow feature
zed-industries/zed pull request #21142
Opened 2024-11-24 15:50 UTC by feeiyu

Closes #20815

Release Notes:
- Enable clangd's dot-to-arrow feature

2024-11-24 16:41 UTC, SomeoneToIgnore requested changes
1. Unfortunately, our CLA bot is broken, so I have to substitute for it for a while: 

> We require contributors to sign our Contributor License Agreement, and we don't have @feeiyu on file. You can sign our CLA at https://zed.dev/cla. Once you've signed, post a comment here that says '@cla-bot check'.

2. Seems that we do not need a custom request, type-less fiddling with `.` and a slight redesign of the approach to make it proper.

2024-11-27 14:02 UTC, feeiyu commented on crates/lsp/src/lsp.rs
> +pub enum LspInitialize {}
yes, but it's not working for the old version of clangd if only fill the experimental field.  Should we consider compatibility?

2024-11-27 14:03 UTC, SomeoneToIgnore commented on crates/lsp/src/lsp.rs
> +pub enum LspInitialize {}
https://github.com/zed-industries/zed/blob/2e21e7585a1aab6c34cc211463871b400c5541ab/crates/languages/src/c.rs#L42-L43

Zed always tries to install the latest stable clangd, so not sure it makes any sense.

2024-11-27 14:15 UTC, feeiyu commented on crates/lsp/src/lsp.rs
> +        callback: Option<Box<dyn FnOnce(&mut Value)>>,
The circular import happened after pass 'adapter: Option<&LspAdapter>' due to `LanguageServer` and `LspAdapter` in different crate `lsp` and `language`.
Maybe we can calculate the InitializeParams outside of initialize.

2024-11-27 14:17 UTC, SomeoneToIgnore commented on crates/lsp/src/lsp.rs
> +        callback: Option<Box<dyn FnOnce(&mut Value)>>,
Sure.
If nothing works, we can do the old way and pass two parameters, but let's avoid the closure that uses `Value`:
* we can either pass another `Option<Value>` for the experimental capabilities (not cool, but we can live with it and I may try and refactor it later)
* or follow your proposal indeed

2024-11-28 08:42 UTC, SomeoneToIgnore approved these changes
Looks much cleaner to me, thank you.

2024-11-28 08:43 UTC, merged