fix: cannot recognize a project that `.git` is soft link
zed-industries/zed pull request #21153
Opened 2024-11-25 03:56 UTC by can2049

Closes #ISSUE

Release Notes:

## background
If a project is big, some times it will be split into many small git repo.
[google repo](https://gerrit.googlesource.com/git-repo/) is a tool to manage a group of git repos.

But, any small git repo manged by this tool, have a difference with normal git repo.
That is , the path `.git` in the root of the git repo, is not a normal directory, but a soft link to real git bare dir.

### zed can not recognize the `git-repo` managed git repos
you can use the procedure to genreate this problem
```
# in some dir, tested on linux
mkdir -p bag_git_repo_project
cd bag_git_repo_project
git init
echo "hello" > hi.txt
git add .
git ci -m "init commit"
echo "hello world" > hi.txt

# modify the repo
mv .git ../.real_git_repo
ln -sf ../.real_git_repo .git
```
with vscode, after opening this project, git work well.
but for Zed, git not work(not git status, no git blame)

## how to fix
libgit2 can recognize git repo from the root of the project(dir that have `.git`).

so, we can recognize the git project by opening from the project root dir, but not the `.git` dir

2024-11-25 08:11 UTC, can2049 commented
@cla-bot check

2024-12-06 22:49 UTC, mikayla-maki approved these changes

2024-12-06 22:57 UTC, mikayla-maki requested changes
Let's add a comment documenting why we use the parent directory here, including a link to the libgit2 documentation:

https://libgit2.org/docs/reference/main/repository/git_repository_open.html

2024-12-07 12:26 UTC, can2049 commented
> Let's add a comment documenting why we use the parent directory here, including a link to the libgit2 documentation:
> 
> https://libgit2.org/docs/reference/main/repository/git_repository_open.html

comment added

2024-12-13 01:57 UTC, mikayla-maki approved these changes

2024-12-13 01:58 UTC, mikayla-maki commented
Thank you!

2024-12-13 02:29 UTC, merged