add word count for markdown files
zed-industries/zed pull request #21263
Opened 2024-11-28 04:03 UTC by saahityaedams

Closes #ISSUE

Release Notes:

- Added word count for markdown files

2024-11-28 04:09 UTC, saahityaedams commented
I've needed to track essay length for some applications.

<img width="1440" alt="Screenshot 2024-11-28 at 9 31 45 AM" src="https://github.com/user-attachments/assets/c5222247-589c-45f5-9a42-420f20efdb13">

2024-11-28 10:44 UTC, HarshNarayanJha requested changes
I might be wrong, but

2024-11-28 13:55 UTC, saahityaedams commented on crates/go_to_line/src/cursor_position.rs
> +                                    .sum::<usize>();
Ack, `t.split_whitespace()` will count markdown elements as words, etc and give a rough word count when markdown elements are involved. On the other hand, I don't think getting the exact word count for markdown files is feasible without some convoluted logic.

If the repo maintainers think the word count needs to be more accurate, I can modify the PR (Off the top of my head, I am thinking I just have to sanitise the text before counting the words)

2024-11-28 15:45 UTC, HarshNarayanJha commented on crates/go_to_line/src/cursor_position.rs
> +                                    .sum::<usize>();
Some way to get the text preview that zed generates and count words in that, if that is performant enough.

2024-12-13 01:54 UTC, mikayla-maki requested changes
Left a note about proper wordcounting above. Integrate that, update the branch, and we'd be happy to merge this :)

2024-12-13 01:54 UTC, mikayla-maki commented on crates/go_to_line/src/cursor_position.rs
> +                                    .sum::<usize>();
Let's use the `unicode_segmentation` crate to calculate this value, by just using `t.unicode_word_indices().count()`. We already depend on this in editor, so it should be easy to use here.

2024-12-13 01:54 UTC, mikayla-maki commented on crates/go_to_line/src/cursor_position.rs
> +        let words = if words.is_some() {
let's use `let words = words.map(|words| { /*...*/ })` here instead

2024-12-13 08:13 UTC, saahityaedams commented on crates/go_to_line/src/cursor_position.rs
> +                                    .sum::<usize>();
@mikayla-maki thanks for your feedback. I like this more accurate approach. One caveat though, the `unicode_segmentation` splits the urls into multiple words while counting (btw I'm fine with it).

2024-12-14 04:23 UTC, mikayla-maki commented on crates/go_to_line/src/cursor_position.rs
> +                                    .sum::<usize>();
I think that's fine. We can only get so accurate.

2024-12-14 04:26 UTC, mikayla-maki requested changes
One more code style nit, and if you could resolve the merge conflict I'll happily merge this!

2024-12-14 04:26 UTC, mikayla-maki commented on crates/go_to_line/src/cursor_position.rs
> +            .map(|words| {
This can just be a `words.filter(|words| words <= 0).map(|words| {(words, "word"})`

2025-01-03 00:54 UTC, mikayla-maki commented
Hello,

As the merge conflict hasn't been resolved in a few weeks, I'm going to close this PR. We're still interested in this feature though! Feel free to re-open the PR once that issue has been fixed :)

2025-01-03 00:54 UTC, closed without merging

2025-01-03 04:11 UTC, saahityaedams commented
I have opened a new PR with the same name #22601 @mikayla-maki