Initial implementation of full bottom dock layout
zed-industries/zed pull request #21337
Opened 2024-11-29 15:14 UTC by th0jensen

Closes #10211

This is a rough implementation at the moment, but can probably/most likely be pushed to main to coincide with terminal pane splitting being released.

![Screenshot 2024-11-29 at 4 13 54 PM](https://github.com/user-attachments/assets/fdfb3079-683d-4abb-9a18-0c6ddfb15c07)

Release Notes:

- Added new layout tree for the bottom dock to have a full layout.
- Added configuration under bottom_dock_layout -> "contained" | "full"

TBA:
- A toggle in the terminal toolbar to enable or disable the behaviour quickly.
- Reimplement the layout to reduce duplicated code.

2024-11-29 20:46 UTC, th0jensen commented
Converted this PR to a draft since I realised it might be desirable with an action in the command pallette or something similar. If someone wants to chime in on any improvements on changes please let me know!

2024-12-06 22:54 UTC, mikayla-maki commented
What is the source for the expand asset you're using in this PR?

2024-12-06 23:14 UTC, th0jensen commented
> What is the source for the expand asset you're using in this PR?

I just asked Zed AI for an SVG that was free to use and would match Zed's other icons in terms of style. I think the decision for which icon to use is ultimately up to you guys, whether this icon fits in or not.

2024-12-12 23:54 UTC, mikayla-maki requested changes
Wow, the AI did a great job on that icon.

That said, we prefer to use [Lucide icons](https://lucide.dev/icons/) when we need new UI buttons. I added some notes about which ones I think we should use and some implementation details.

2024-12-12 23:54 UTC, mikayla-maki commented on crates/workspace/src/dock.rs
> +    use_full_width: bool,
I don't think we want this to be configurable for each individual Dock. Rather, this seems like a variable that should be on the Workspace itself.

2024-12-12 23:54 UTC, mikayla-maki commented on assets/icons/expand_horizontal.svg
Let's use Lucide's `chevrons-left-right` and  `chevrons-right-left` for this instead of this icon

2024-12-12 23:54 UTC, mikayla-maki commented on crates/terminal_view/src/terminal_panel.rs
> +                        IconButton::new("toggle_extended", IconName::ExpandHorizontal)
Let's make this button's icon swap between Lucide's `chevrons-left-right` and `chevrons-right-left`

2024-12-13 19:47 UTC, th0jensen commented
Thanks for the input on the icons! I moved the property that was on the dock to the workspace, as well as changing out the icons :)

2024-12-14 04:30 UTC, mikayla-maki commented
Awesome! Looks like there's a merge conflict, and could you include a screenshot showing the button you added?

2024-12-17 22:12 UTC, th0jensen commented
After adding the left-contained variant I decided to add in both alignments so people can choose what they prefer. So I thought this was the best way to implement the button, but I'm not quite sure. I encountered a lot of "Rustisms" I didn't quite understand, but hey, it runs!

I haven't noticed any weird behaviours or bugs when testing the builds, but I feel like the implementation in `crate/terminal_view/terminal_panel.rs` is a bit non-optimal.

This is what the button looks like:
<img width="273" alt="Screenshot 2024-12-17 at 11 08 24 PM" src="https://github.com/user-attachments/assets/eb36cb19-5c90-4461-a21c-d8370e7f8203" />

2024-12-18 00:17 UTC, th0jensen commented
I also feel like I could use the lucide icon `columns-3` and shade which space the bottom bar will occupy. I'd display this next to the labels in the dropdown menu, but it would require adding a new method to `crate/ui/context_menu.rs`:

The method `toggleable_entry()` already has a configurable `icon: None`, so I imagine I could just expose that as a parameter in a different method, something like `toggleable_entry_with_icon`?

This may be too much effort for a feature that I imagine most people will just configure in settings and leave be...

2024-12-19 22:21 UTC, mikayla-maki commented
Hmm, I think this is a good feature but I don't quite like the look of that menu yet, cc: @danilo-leal, @iamnbutler, how do you think we could incorporate these?

For reference, VSCode uses a button in the top right of the title bar, and that button opens up a menu with an overall layout menu:

<img width="533" alt="Screenshot 2024-12-19 at 2 19 48 PM" src="https://github.com/user-attachments/assets/944679b7-7c61-4e71-866c-926c61ff019c" />

2024-12-20 16:47 UTC, th0jensen commented
> For reference, VSCode uses a button in the top right of the title bar, and that button opens up a menu with an overall layout menu

I think this makes sense too. It feels unnatural to have the layout control on the dock when the property pertains to the workspace itself- and changing the value does change the button's origin, which is horrible for UX:

If someone wants to change the layout on the current build, they'll have to chase the button around in order to reset or change the layout.

I have noticed that VS Code also has this in the Menu Bar -> View -> Layout (something like this)

2024-12-27 03:55 UTC, iamnbutler commented
While it looks really small, this is a pretty massive change from our standpoint, as all UI in zed thus-far has been designed and build from the perspective of sidebars always extending the full height of the window.

I'm not against us exploring it, but it'll probably have to wait until after the holidays before I can take the time to look into this and give proper feedback.

Thanks for the patience!

2025-01-21 16:04 UTC, iamnbutler commented
Hey @th0jensen sorry for the huge delay, I haven't been good at getting back to review these PRs. 

I'll take a look at this one today, there are a few design nits I have but I might be able to tidy them up quickly, otherwise I'll jump back in here and add some feedback.

2025-01-21 16:32 UTC, iamnbutler commented
@th0jensen It looks like the latest commit doesn't compile for me. Can you let me know once it is runnable and I'll take a look, thanks!

2025-01-21 17:25 UTC, th0jensen commented
Hey @iamnbutler! Thanks for taking a look at the PR :)

The current commit *should* build. I haven't been able to finish building it myself since I'm on the way out of the house, I'll check up on it in a few hours, but if you want to check it out before that, here you go.

2025-01-21 22:01 UTC, th0jensen commented
@iamnbutler The latest commit currently builds :)

2025-03-01 08:21 UTC, ColorFuzzy commented
I really hope this feature. On a 13.5-inch computer, the terminal window is super small with ai panel opened. It's a real pain. Thanks a lot!

2025-03-06 10:42 UTC, closed without merging

2025-03-06 12:16 UTC, th0jensen commented
The PR has been moved to #26211