Improve `editor: open url` command to open the selected portion of url
zed-industries/zed pull request #21825
Opened 2024-12-10 19:50 UTC by 0xtimsb

Closes #21718

Just like in Vim, if a URL is selected, it opens exactly that portion of the URL. Otherwise, if only the cursor is on a URL, it opens the entire URL.

Zed currently does the latter. This PR also adds support for the former.

https://github.com/user-attachments/assets/8bdd2952-ceec-487c-b27a-5cea4258eb03

Release Notes:

- Updated the `editor: open url` to also handle the selected portion of a URL.

2024-12-10 20:14 UTC, 0xtimsb commented
Some edge cases I tested apart from obvious ones:

- Leading/trailing whitespace around a selected URL is allowed
- Only single URL should be selected
- Both forward and backward selections should work

2024-12-12 22:55 UTC, mikayla-maki requested changes

2024-12-12 22:55 UTC, mikayla-maki commented on crates/editor/src/editor.rs
> +            cx.spawn(|editor, mut cx| async move {
Could we reduce the duplication here by moving the `head == tail` check inside the spawn call?

2024-12-13 05:59 UTC, 0xtimsb commented
Thanks! Let me know if this works.

2024-12-13 06:14 UTC, mikayla-maki approved these changes

2024-12-13 06:15 UTC, mikayla-maki commented
Thanks!

2024-12-13 06:15 UTC, merged