feat: copy current file name
zed-industries/zed pull request #22174
Opened 2024-12-18 03:54 UTC by ankddev

Closes #21967

## Description
This PR adds commands to copy current file's name.

## Screenshots
### Project View
![image](https://github.com/user-attachments/assets/c3dd10af-b01e-44f6-a741-e75275f9591c)
### Editor command (command palette)
![image](https://github.com/user-attachments/assets/83f1693c-10c4-4058-b0e1-b0e166fa6bfa)
### Tab's menu
![image](https://github.com/user-attachments/assets/d4f6522b-7f18-4d8f-8809-e955a0741e88)

Release Notes:

- Added commands to copy current file name

2024-12-18 15:22 UTC, notpeter commented
1. I don't think this is not a common enough operation that it deserves placement in default the project_panel or tab right click menu.

2. Probably the action names should reversed so it's `CopyFileName` and `CopyFileNameWithoutExtension`. As I would assume the `CopyFileName` action would give me the  filename, not a truncated version of it.

2024-12-18 16:33 UTC, ankddev commented
Okay, I will do it tommorow.

2024-12-19 03:42 UTC, ankddev commented
@notpeter I renamed commands and removed them fom tab's menu. Should I also remove these commands from project_panel's menu?

2025-01-24 14:22 UTC, ankddev commented
@notpeter Any updates on this PR's state?

2025-01-25 11:21 UTC, ankddev commented
I accidently removed all commits and force-pushed branch 🤣
Now I restored all changes.

2025-02-11 06:41 UTC, marcospb19 approved these changes
I can't think of an use-case for `CopyFileNameWithoutExtension`, other than that it looks good.

2025-02-11 11:35 UTC, ankddev commented
@marcospb19 Original issue author said that it is useful when creating single export module component/util files etc.

2025-02-11 14:55 UTC, marcospb19 requested changes

2025-02-11 14:55 UTC, marcospb19 commented on crates/editor/src/editor.rs
> +    pub fn copy_file_name(
@ankddev I was going to merge but CI is red, you need to run `cargo fmt`, I believe.

2025-02-11 15:05 UTC, ankddev commented on crates/editor/src/editor.rs
> +    pub fn copy_file_name(
Done

2025-02-11 15:08 UTC, marcospb19 approved these changes
Let's see if CI is happy now.

2025-02-11 15:27 UTC, ankddev commented
@marcospb19 It's successful now

2025-02-11 15:42 UTC, merged

2025-06-22 21:02 UTC, spiff1281 commented
> I can't think of an use-case for `CopyFileNameWithoutExtension`, other than that it looks good.

DBT takes the name of the file without extension.

2025-06-22 21:10 UTC, spiff1281 commented
I am trying to understand if the feature is in the product...how do I copy only the file name?

2025-06-22 23:28 UTC, notpeter commented
> I am trying to understand if the feature is in the product...how do I copy only the file name?

You can trigger it from the command palette (cmd-shift-p)
<img width="296" alt="Screenshot 2025-06-22 at 19 24 18" src="https://github.com/user-attachments/assets/8d1906fe-c592-4950-9562-0a03c38f0758" />

You can bind it in your keymap:
```json
  {
    "context": "Editor",
    "bindings": {
      "cmd-alt-ctrl-c": "editor::CopyFileNameWithoutExtension"
    }
  }
```