Add dirty indicator to Breadcrumbs
zed-industries/zed pull request #22418
Opened 2024-12-25 14:38 UTC by Qkessler

## Change Summary

Users commonly remove the Tab Bar to remove noise while they write/code. I do it myself. Nevertheless, there's a gap in visibility over the current pane when one disables the tab bar: we miss the dirty indicator on the current pane. When I change something without saving, there's no visual indicator that the pane was changed, leading to potential mistakes.

With this PR, I propose using the `Breadcrumbs` for that. It commonly includes the buffer/file name, even if the outline doesn't show an inner element. By adding the indicator on the Breadcrumbs, we ensure people who choose to remove the tab bar still have the visibility while maintaining the display minimal.

I'm open to adding this behind a configuration flag. I'd even be good for both the tab bar and the breadcrumbs to share that configuration option, to avoid duplication.

Closes https://github.com/zed-industries/zed/issues/22390

## Risks associated with this change

This change introduces a different usage of the Breadcrumbs. I see little risk, considering using the left of the breadcrumbs is non-obstrusive.

## Testing

To test it, I made the changes and spawn a Zed instance with `RUST_LOG=debug scripts/zed-local -1`. Here's what the pane looks like without the change:

<img width="866" alt="image" src="https://github.com/user-attachments/assets/46495715-3d55-4281-a16b-a65073d6c04b" />

and here's what it looks after, whenever I make a change on the file and don't save:

<img width="866" alt="image" src="https://github.com/user-attachments/assets/a6fb7311-37dc-410e-8073-bb32d3219a27" />

Release Notes:

- Added file change Indicator on Breadcrumbs

2024-12-25 14:39 UTC, Qkessler commented
@danilo-leal , interested in your thoughts for this change. Let me know what you think coming from the UX perspective.

2024-12-26 01:56 UTC, 0x2CA commented
Thank you for your work, there is an indicator that is very good, but it will cause the original text to move to the right as a whole, is this appropriate? I think using color markers to mark the path would be better, wouldn't it?

2024-12-26 05:18 UTC, bonniesimon commented
I have a few suggestions:

Have the marker on the right side (This is what VsCode does):

![image](https://github.com/user-attachments/assets/51988161-7769-444c-888e-96c4cb190c4c)

Have the marker at the end of the breadcrumbs:
![image](https://github.com/user-attachments/assets/97961b88-feb7-415d-9665-277ceba1a0d6)

2024-12-26 07:23 UTC, Qkessler commented
Thanks both for the suggestions, great ones. Interested in hearing from @danilo-leal , who has context on the direction for Zed's design.

2025-01-04 00:17 UTC, mikayla-maki commented
cc: @iamnbutler

2025-01-04 22:27 UTC, danilo-leal commented
Hey! Thanks for the PR @Qkessler, appreciate it! 😊 I pushed a change agreeing with @bonniesimon's second suggestion, as that doesn't make the actual breadcrumb text/content jump around when the dirty indicator is present. Design's looking good to me, but functionality-wise, I'd make the dirty indicator _not_ visible if `"tab_bar": { "show": true }`, otherwise, we have this redundant scenario:

<img width="350" alt="Screenshot 2025-01-04 at 7 27 07 PM" src="https://github.com/user-attachments/assets/2d725c49-1bd7-4525-afdd-10499e71f703" />

2025-01-05 06:34 UTC, Qkessler commented
That looks good, mentioned the risk on the change summary! Do you want me to pick-up showing the indicator based on the configuration option?

2025-01-05 07:21 UTC, Qkessler commented
Nevermind, did it myself! Let me know what you think. The indicator is successfully hidden when the tab bar is there and shown otherwise.

2025-01-07 01:06 UTC, mikayla-maki requested changes

2025-01-07 01:06 UTC, mikayla-maki commented on crates/breadcrumbs/src/breadcrumbs.rs
> +        let dirty_indicator = pane::render_item_indicator(active_item.boxed_clone(), cx);
Since this uses an &cx, can we move it into the `then(|| {})` close below?

2025-01-08 19:13 UTC, Qkessler commented on crates/breadcrumbs/src/breadcrumbs.rs
> +        let dirty_indicator = pane::render_item_indicator(active_item.boxed_clone(), cx);
For sure, happy to make the change. Interested to learn more about your tribal knowledge. Is it really expensive to perform operations on the `&mut cx`? Any more reading of the codebase you recommend?

2025-01-08 19:17 UTC, Qkessler commented
Published the change. Tested again with `RUST_BACKTRACE=1 RUST_LOG=info script/zed-local -1` and running through the 1. scenario with tab bar on 2. tab bar off. The indicator is only shown in #2.

2025-01-11 15:09 UTC, Qkessler commented
Hi all! @mikayla-maki , let me know if you need anything else from my side. Happy to continue forward with this change otherwise.

2025-01-30 19:34 UTC, mikayla-maki requested changes
Once @iamnbutler suggestions are implemented, let's review this PR again :)

2025-02-26 18:46 UTC, closed without merging

2025-05-03 02:05 UTC, bonniesimon commented
Any one working on this? :(

2025-05-11 14:11 UTC, ViveK-PothinA commented
I raised a new PR - #30507 based off @iamnbutler design https://github.com/zed-industries/zed/pull/22418#issuecomment-2605253667