Show highlighted symbol in the scrollbar
zed-industries/zed pull request #7029
Opened 2024-01-29 23:37 UTC by fxsalazar

Release Notes:

- Added highlighted symbols to the scrollbar; partially mentioned in:
  - https://github.com/zed-industries/zed/issues/5308
  - https://github.com/zed-industries/zed/issues/4866

2024-01-29 23:37 UTC, fxsalazar commented
@cla-bot check'

2024-01-30 05:14 UTC, mikayla-maki approved these changes
Thank you for this addition!

2024-01-30 05:17 UTC, mikayla-maki requested changes

2024-01-30 05:17 UTC, mikayla-maki commented on crates/editor/src/element.rs
> +            if layout.is_singleton && scrollbar_settings.symbols_selections {
Above here, there's a check for 'show_scrollbars', that wasn't updated to incorporate this new information. Could you add a branch to resolution of the `ShowScrollbar::Auto` setting, on line 2066?

2024-01-30 18:13 UTC, mikayla-maki requested changes

2024-01-30 18:13 UTC, mikayla-maki commented on crates/editor/src/element.rs
> +                    (is_singleton && scrollbar_settings.symbols_selections && editor.has_background_highlights::<BufferSearchHighlights>())
I believe this should be `DocumentHighlightRead` or `DocumentHighlightWrite`, as shown in `Editor::refresh_document_highlights`

2024-01-30 21:50 UTC, mikayla-maki approved these changes

2024-01-30 21:57 UTC, mikayla-maki commented
Thank you!

2024-01-30 21:57 UTC, merged