terminal: Fix copy to clipboard lag
zed-industries/zed pull request #7323
Opened 2024-02-03 13:57 UTC by N8th8n8el

Fixes #7322

Note: I don't know much Rust (yet) and I also believe that this isn't a general fix of the underlying issue. There might be more of the same issue here, e.g. clearing the terminal (via CMD+K) also has a significant delay sometimes (whenever you get unlucky and the time to the next paint is long).

I'm happy to try to fix this properly with some guidance.

2024-02-03 13:58 UTC, N8th8n8el commented
@cla-bot check

2024-02-05 08:40 UTC, mrnugget commented
So is the idea here that you skip the event loop entirely? Is there no alternative solution possible where we wake up the event loop listener on certain events?

2024-02-05 10:13 UTC, N8th8n8el commented
> So is the idea here that you skip the event loop entirely? Is there no alternative solution possible where we wake up the event loop listener on certain events?

If by event loop you mean paint loop (at least that is my current understanding) then yes.
As stated in the issue, I feel like waiting for (or triggering) paint to copy something into the clipboard doesn't make sense. Ifaics copying to the clipboard has no effect on what is rendered, so why do we need to (wait for) paint?

Maybe it makes more sense if we also take other events into account though, such as clearing the terminal which does have an effect on what is rendered.

2024-02-05 10:18 UTC, mrnugget commented
> If by event loop you mean paint loop (at least that is my current understanding) then yes.
> As stated in the issue, I feel like waiting for (or triggering) paint to copy something into the clipboard doesn't make sense. Ifaics copying to the clipboard has no effect on what is rendered, so why do we need to (wait for) paint?

I don't think the event loop in the terminal is strictly about rendering/painting. It's about the state of the terminal itself.

And this bug (and others that have popped up) make me think that maybe something with the event loop and how often it runs is broken, not just with the copy behaviour itself.

2024-02-05 10:25 UTC, nathanael-ruf commented
> And this bug (and others that have popped up) make me think that maybe something with the event loop and how often it runs is broken, not just with the copy behaviour itself.

Yes it's not just copying (that's
>I also believe that this isn't a general fix of the underlying issue

---

> I don't think the event loop in the terminal is strictly about rendering/painting. It's about the state of the terminal itself.

`terminal.sync(cx);` is called in `TerminalElement:compute_layout` which is called in `TerminalElement:paint`. I don't know yet how GPUI works, i.e. how it decides when to paint, but from the name it sounds like this is just about painting and e.g. copying to the clipboard shouldn't trigger a repaint (maybe?).

2024-02-05 10:25 UTC, N8th8n8el commented
> And this bug (and others that have popped up) make me think that maybe something with the event loop and how often it runs is broken, not just with the copy behaviour itself.

Yes it's not just copying (that's
>I also believe that this isn't a general fix of the underlying issue

---

> I don't think the event loop in the terminal is strictly about rendering/painting. It's about the state of the terminal itself.

`terminal.sync(cx);` is called in `TerminalElement:compute_layout` which is called in `TerminalElement:paint`. I don't know yet how GPUI works, i.e. how it decides when to paint, but from the name it sounds like this is just about painting and e.g. copying to the clipboard shouldn't trigger a repaint (maybe?).

2024-02-05 19:00 UTC, mikayla-maki commented on crates/terminal/src/terminal.rs
> -            InternalEvent::Copy => {
I don't think we should remove this, as we'd like to be cooperative and give the PTY time to write into the Terminal.

That said, I think the better solution would be to...

2024-02-05 19:00 UTC, mikayla-maki requested changes

2024-02-05 19:00 UTC, mikayla-maki commented on crates/terminal_view/src/terminal_view.rs
> -        self.terminal.update(cx, |term, _| term.copy())
Add a `cx.notify()` here to schedule the re-render.

2024-02-05 19:10 UTC, mikayla-maki commented
The deeper solution to this problem IMO is to take ownership of the Alacritty event loop code and let it own the alacritty Terminal struct. Then we can send everything in the existing, poorly named, `EventLoop` struct to the Alacritty terminal as messages that can be replied to instantly. 

Lacking that refactoring though, I think we should stick to the current solution which maintains the relative ordering of events in time.

2024-02-05 19:48 UTC, mikayla-maki approved these changes

2024-02-05 20:06 UTC, merged