Fix code actions support for elm-language-server
zed-industries/zed pull request #7635
Opened 2024-02-09 21:45 UTC by w0rm

This PR makes code actions in elm-language-server work and probably fixes this for other language servers that do not populate the `edit` or `command` action property right away. This didn't work before:

![unexpose](https://github.com/zed-industries/zed/assets/43472/4879130d-b10d-49aa-9863-bf92c761f816)

After comparing actions from elm-language-server to rust-analyzer, we realized that they have different content in the `data` property.

```json
// elm-language-server:
{"jsonrpc":"2.0","id":62,"result":[{"title":"Expose Function","kind":"refactor","data":{"actionName":"expose_function","refactorName":"expose_unexpose","uri":"file:///Users/unsoundscapes/Src/Github/elm-pool/src/Game.elm","range":{"start":{"line":121,"character":2},"end":{"line":121,"character":2}}},"isPreferred":true}]}

// rust-analyzer:
{"jsonrpc":"2.0","id":52,"result":[{"title":"Generate a documentation template","kind":"","data":{"codeActionParams":{"textDocument":{"uri":"file:///Users/unsoundscapes/Src/Github/zed/crates/zed/src/languages/elm.rs"},"range":{"start":{"line":42,"character":10},"end":{"line":42,"character":10}},"context":{"diagnostics":[],"only":["","quickfix","refactor","refactor.extract","source"]}},"id":"generate_documentation_template:Generate:0"}}]}
```

The LSP spec allows any content in the `data` property, but [the current implementation in Zed](https://github.com/zed-industries/zed/blob/efe23ebfcdd653b13be79132b1e2925bcd7bde45/crates/project/src/project.rs#L5142) checks that `data.codeActionParams.range` should exist, and only then it resolves the action from the language server. This assumption is most likely coming from [rust-analyzer implementation](https://github.com/rust-lang/rust-analyzer/blob/bb0de88f24cc3a8de10837585fbb8172f6859752/crates/rust-analyzer/src/lsp/ext.rs#L445).

What should be the right condition to check in order to resolve the action? [Zed declares](https://github.com/zed-industries/zed/blob/efe23ebfcdd653b13be79132b1e2925bcd7bde45/crates/lsp/src/lsp.rs#L523) that it supports resolve for `edit` and `command` properties. If both are none, it is safe to assume that an action needs to be resolved.

Regarding patching the `range` property, we are not exactly sure why it was necessary, but we've implemented support for elm-language-server. Maybe this custom functionality should be extracted into an LSP adapter?

Release Notes:

- Fix code actions support for elm-language-server.

2024-02-14 22:02 UTC, w0rm commented
According to the discussion in https://github.com/microsoft/language-server-protocol/issues/1136#issuecomment-724808037 the correct logic seems to be if `edit` and/or `command` is missing, then resolve the code action.

I wonder though if this could break the existing lsp integrations.

2024-03-05 08:57 UTC, SomeoneToIgnore requested changes
Sorry for paying attention for this PR now only, but thank you a lot for another angle on the issue, after https://github.com/zed-industries/zed/pull/8874 and this one, I've started to understand what's wrong with current Zed's approach better.

In the specification, 
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeAction

it mentions that 

```
/**
 * A data entry field that is preserved on a code action between
 * a `textDocument/codeAction` and a `codeAction/resolve` request.
 *
 * @since 3.16.0
 */
data?: LSPAny;
```

so the whole point of type erasure in this type is to avoid server accessing it.
So, whatever the code here did already is wrong, and I do not think we should continue doing this with this PR.

What is seems plausible is to check which fields Zed allows resolving
https://github.com/zed-industries/zed/blob/4b2e7745945bbffb5e1e9b7c5825c693d8034607/crates/lsp/src/lsp.rs#L573
(which is odd too, I would add `diagnostics` there, at least)

and check those fields before the resolution request: if `data` is present and any of the fields is absent — we might need to query the resolution.
In case of actions, those are invoked manually with and selected from the list, so it's not a very frequent operation — we can allow sending extra resolve requests relatively safely.

I'm also confused by the test adjustments in this PR: I would expect this fix to add more tests with the thing that it fixed (e.g. the LSP response copy from elixir langserver)

Recently, there had appeared another PR that seems to approach the same issue, but from a more spec-compliant angle:
https://github.com/zed-industries/zed/pull/8874

So I wonder, should we close this PR and concentrate on the other one to fix the issue?

2024-03-05 09:14 UTC, closed without merging

2024-03-05 20:52 UTC, SomeoneToIgnore commented
I have created https://github.com/zed-industries/zed/pull/8904 as a follow-up.

CI in https://github.com/zed-industries/zed/actions/runs/8162482546?pr=8904 had bundled an artifact with the fix: https://github.com/zed-industries/zed/actions/runs/8162482546/artifacts/1299954625 could you download that and check that it fixes the issue for you?

2024-03-06 06:35 UTC, w0rm commented
@SomeoneToIgnore I confirm that it's working now. Thanks for the fix!