Update configuring_zed__key_bindings.md
zed-industries/zed pull request #7953
Opened 2024-02-17 16:11 UTC by vuhctreh

Clarified how to apply pre-defined bindings to your IDE.
I don't think it's immediately obvious this is what you need to do so just made it painfully obvious
in the README.

Release Notes:

- Added/Fixed/Improved ... ([#<public_issue_number_if_exists>](https://github.com/zed-industries/zed/issues/<public_issue_number_if_exists>)).

**or**

- N/A

Optionally, include screenshots / media showcasing your addition that can be included in the release notes.

2024-02-17 20:32 UTC, SomeoneToIgnore reviewed
Let's clarify a few things here:

> You may apply these key bindings to your own IDE by pasting the pre-defined keymaps into your keymap.json config.


* 
> You may apply

This wording is odd — as if it generously allows you to apply something, I would use `you can apply` instead, it's more neutral.

* 
> your own IDE

Is this supposed to mean Zed? 
I would omit the entire phrase since it removes a lot of questions (is Zed an IDE? which IDE is meant here, etc.) and does not change meaning of the phrase.

* 
Main question: is the intended goal of copy-pasting to use different keybindings as defaults?

We seem to have better ways to do that: 
1. clicking this bullet on the welcome screen
<img width="1216" alt="image" src="https://github.com/zed-industries/zed/assets/2690773/30a8b1af-150b-4e2a-935c-4f6e1da3e812">

2. invoking this action anytime in Zed:
<img width="674" alt="image" src="https://github.com/zed-industries/zed/assets/2690773/c097c208-3ea4-4c25-9e7c-0a7d76b0d849">

Either of these opens this modal
<img width="626" alt="image" src="https://github.com/zed-industries/zed/assets/2690773/c960ec4d-af93-4869-9d69-3d2403651d0b">

and is supposed to make change keybindings according to those keymaps.
Example:

Atom keymap as a base:
<img width="607" alt="image" src="https://github.com/zed-industries/zed/assets/2690773/b3185ceb-39a2-49d6-bd3b-3abc45597dc5">

JB keymap as a base:
<img width="558" alt="image" src="https://github.com/zed-industries/zed/assets/2690773/39ecd1f9-e3d2-4b2d-8ab5-325e505bc4d7">

So, seems to work for me.
Is the copying proposed in this change doing the same? If so, I think we'd better make a different thing painfully obvious instead of proposing the copy-pasting.

2024-02-17 20:33 UTC, SomeoneToIgnore requested changes
Missed the button, requesting changes, see the comment above.

2024-02-18 15:24 UTC, SomeoneToIgnore commented
Much better, thank you.
Let's satisfy the cla checker and merge it.

2024-02-18 15:28 UTC, vuhctreh commented
@cla-bot check

2024-02-18 15:33 UTC, merged