Zig outline view
zed-industries/zed pull request #8122
Opened 2024-02-21 13:27 UTC by StringNick

Release Notes:

- Added Zig outline view, related #7357 
- 
<img width="762" alt="image" src="https://github.com/zed-industries/zed/assets/13052752/a879cd98-d5e0-446e-aaed-504528b99552">

2024-02-21 14:05 UTC, StringNick commented
@cla-bot check

2024-02-22 18:03 UTC, maxbrunsfeld commented
It looks like there's a spelling typo in the highlight query. Could you take a look at that @StringNick ?

2024-02-22 18:04 UTC, maxbrunsfeld requested changes

2024-02-22 18:04 UTC, maxbrunsfeld commented on crates/zed/src/languages/zig/highlights.scm
> +] @variable
I think we usually use `@property` for struct fields / members. Would that make sense here?

2024-02-22 18:05 UTC, maxbrunsfeld commented
This is a great improvement. I left a couple suggestions.

2024-02-22 23:07 UTC, StringNick commented
done

2024-02-23 20:37 UTC, maxbrunsfeld commented
It looks like there's another typo in the highlights query.

2024-02-26 17:25 UTC, maxbrunsfeld commented
There's still a typo being caught in CI. Can you run `typos` locally?

2024-03-01 01:24 UTC, merged

2024-03-01 01:24 UTC, maxbrunsfeld commented
Thanks @StringNick !