Introducing file_id on windows
zed-industries/zed pull request #8130
Opened 2024-02-21 16:33 UTC by JunkuiZhang

Release Notes:

- Added a function `file_id` to get the file id, which is similar to inode on unix sys.

2024-02-21 16:36 UTC, JunkuiZhang commented
@cla-bot check

2024-02-21 18:02 UTC, mikayla-maki requested changes

2024-02-21 18:02 UTC, mikayla-maki commented on crates/fs/src/fs.rs
> +    let file = std::fs::OpenOptions::new()
We shouldn't be doing synchronous file opening here, this needs to be swapped to use `smol::fs`

2024-02-21 18:02 UTC, mikayla-maki commented on crates/fs/src/fs.rs
> +        let inode = file_id(path);
We already open the file above using smol, can we restructure this code somehow to not open the file twice?

2024-02-22 17:36 UTC, mikayla-maki requested changes
Looks good! Just a few small changes :)

2024-02-22 18:08 UTC, JunkuiZhang commented on crates/fs/src/fs.rs
> +    let ret = unsafe { GetFileInformationByHandle(file.as_raw_handle() as HANDLE, &mut info) };
I'm sorry, I'm not particularly familiar with async. Thank you very much for your review; it has taught me a lot!

2024-02-22 18:11 UTC, JunkuiZhang commented on crates/fs/src/fs.rs
> +async fn file_id(path: impl AsRef<Path>) -> u64 {
Your review has given me a much better understanding of what truly constitutes good code, and what good codes should be like, thx!

2024-02-22 18:51 UTC, mikayla-maki approved these changes

2024-02-22 19:22 UTC, merged