added tsx and jsx icons
zed-industries/zed pull request #8470
Opened 2024-02-27 08:39 UTC by ashraf7hossain

Release Notes:

- Added  ([#<public_issue_number_if_exists>](https://github.com/zed-industries/zed/issues/<public_issue_number_if_exists>)).

**or**

- N/A

Optionally, include screenshots / media showcasing your addition that can be included in the release notes.

2024-02-27 09:46 UTC, ashraf7hossain commented
added some essential icons to the project.

2024-02-27 13:32 UTC, maxdeviant requested changes
The C++ and C# icons are too large in comparison with our other icons.

Additionally, all of the icons should be provided with a plain black stroke and full color. The icons themselves should not have colors.

2024-02-27 14:36 UTC, Imgkl commented
@ashraf7hossain Please make the icons 14x14, so that it's consistent with other icons.

Also I think you've forgot to add icons path under `types`. You've only added the suffix.

2024-02-28 10:38 UTC, ashraf7hossain commented
changed icons size to 14x14 and also added type

2024-02-28 15:57 UTC, maxdeviant commented
> changed icons size to 14x14 and also added type

We still need to change the icons to black and white. They still have color.

Also, I think at least the C++ icon (and maybe the C# one) are going to have the same problem I mentioned here https://github.com/zed-industries/zed/pull/8272#issuecomment-1965716583, where the icon doesn't look good in Zed.

2024-02-29 13:55 UTC, ashraf7hossain commented
changed color to black and white and added suitable icons.

2024-02-29 14:05 UTC, maxdeviant commented on assets/icons/file_icons/cs.svg
It looks like there's some visual artifacting going on with this icon:

<img width="24" alt="Screenshot 2024-02-29 at 9 05 01 AM" src="https://github.com/zed-industries/zed/assets/1486634/94b46b95-e1ac-44b6-8036-37f3ffa1b06e">

<img width="92" alt="Screenshot 2024-02-29 at 9 05 12 AM" src="https://github.com/zed-industries/zed/assets/1486634/406ee8c2-0de8-4e91-8d56-05695be543f5">

2024-02-29 14:06 UTC, maxdeviant commented on assets/icons/file_icons/cpp.svg
> +<image id="image0_5_6" width="512" height="512" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAQAAABecRxxAAAYeklEQVR42u3dfbRV5X3g8e89cHkREPCiAqJeNEGjgElEo0CSxqLVJGhLxJUYNU0mJel0I
We'll need to change this to be a true SVG.

Right now it looks like the SVG has a PNG embedded inside of it, which isn't what we want.

2024-02-29 14:07 UTC, maxdeviant commented on assets/icons/file_icons/jsx.svg
> +<image id="image0_5_19" width="512" height="456" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAHICAMAAAAP9aKMAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAA
Same thing here.

We need a true SVG, not and SVG containing a PNG.

2024-03-02 10:05 UTC, ashraf7hossain commented
I have added pure svg icons for jsx,cpp and cs and here is the resource 
[link](https://www.figma.com/file/6YOKMaNFlWc7ikJ164UdJI/Untitled?type=design&node-id=0-1&mode=design&t=DJ0rtZnZ9ikleyOV-0)

2024-03-02 15:28 UTC, Imgkl commented
@ashraf7hossain Great that you figured out the SVG issue. One more issue I'd like to point out, Look at the icons below as reference. I found your current JSX icon is not similar to what the react framework has. 

<img width="200" alt="image" src="https://github.com/zed-industries/zed/assets/25414681/741c240c-654b-427b-adfc-dd5269306973"> 
<img width="101" alt="image" src="https://github.com/zed-industries/zed/assets/25414681/3ca78999-6246-4888-99df-bde4feaab984">



React - https://www.svgrepo.com/vectors/react/
C++ - https://www.svgrepo.com/svg/521339/c-plusplus-16
c# - https://www.svgrepo.com/svg/521273/c-sharp-16

2024-03-02 15:49 UTC, ashraf7hossain commented
Now should I only change react icon or all icons I that I uploaded?

2024-03-04 13:51 UTC, ashraf7hossain commented
I have updated react icon please let me know if it works .

2024-03-04 15:51 UTC, maxdeviant commented
The C++ and C# icons still don't look good enough to accept. I think we should drop them from this PR and focus on just the TSX and JSX icon.

That one is getting closer, but it still doesn't align with our other icons. It seems like it's almost stretched horizontally.

<img width="217" alt="Screenshot 2024-03-04 at 10 48 17 AM" src="https://github.com/zed-industries/zed/assets/1486634/677a6bf2-d15c-4bca-a11b-fa299f404ee2">

Where did we source that one from?

2024-03-06 09:52 UTC, ashraf7hossain commented
I changed react icon and removed c++ and c# icons , please let me know if it is required something?

2024-03-14 17:18 UTC, maxdeviant commented
The icon still doesn't look quite right:

<img width="154" alt="Screenshot 2024-03-14 at 1 17 02 PM" src="https://github.com/zed-industries/zed/assets/1486634/8581dc50-1b0a-409e-b6e0-041aae78e2ce">

I think I'm going to close this until we can design a TSX/JSX icon for our existing icon theme.

2024-03-14 17:18 UTC, closed without merging