windows: get current display size
zed-industries/zed pull request #8916
Opened 2024-03-06 00:16 UTC by intigonzalez

For the moment the windows port has a single display with hard-coded values.

This first PR is just to at least fetch the **actual size of the current display**. The idea
is using this code as a first template to start getting familar with the code base
and prepare the work for enumerating all displays.

2024-03-06 00:17 UTC, intigonzalez commented
@cla-bot check

2024-03-06 19:12 UTC, mikayla-maki requested changes

2024-03-06 19:12 UTC, mikayla-maki commented on crates/gpui/src/platform/windows/display.rs
>      // todo!("windows")
Please remove this TODO

2024-03-07 01:47 UTC, mikayla-maki approved these changes

2024-03-07 02:12 UTC, mikayla-maki commented
CI failure looks spurious, merging.

2024-03-07 02:12 UTC, merged