Add clipboard support for Windows
zed-industries/zed pull request #8978
Opened 2024-03-07 01:53 UTC by EricApostal

Release Notes:

- Added Read / Write clipboard support to Windows via copypasta

2024-03-07 02:11 UTC, mikayla-maki requested changes

2024-03-07 02:11 UTC, mikayla-maki commented on .gitignore
> -.idea
Please restore this `.gitignore`

2024-03-07 02:11 UTC, mikayla-maki commented on crates/gpui/Cargo.toml
> +copypasta = "0.10.1"
This should be moved to the `[target.'cfg(any(target_os = "linux", target_os = "windows"))'.dependencies]` section.

2024-03-07 02:56 UTC, EricApostal commented
These issues should be resolved, sorry about that.

2024-03-07 02:57 UTC, mikayla-maki commented
Please also resolve the merge conflicts!

2024-03-07 03:17 UTC, EricApostal commented
> Please also resolve the merge conflicts!

I've synced with upstream now :)

2024-03-07 03:21 UTC, EricApostal commented
@cla-bot check

2024-03-07 03:36 UTC, mikayla-maki approved these changes

2024-03-07 03:44 UTC, mikayla-maki commented
I think you updated the Cargo.lock a bit too much for Zed right now. Try restoring it from main, then running cargo check, and seeing what happens?

2024-03-08 00:08 UTC, mikayla-maki approved these changes

2024-03-08 00:10 UTC, mikayla-maki commented
Hmmm, it looks like things are still a bit broken, can you double check? I also pushed a `cargo fmt` to this fork FYI

2024-03-08 03:11 UTC, EricApostal commented
I am sorry about that, I messed up my compile target and misunderstood the style check fail. I've fixed the imports and verified that all implemented functionality works as expected on Windows.

2024-03-08 03:18 UTC, EricApostal commented
I'd also like to note that I really do apologize for some of the carelessness in this PR- all of these problems should have been avoided ahead of time by doing more research beforehand. I appreciate how patient you've been with me 😄 .

2024-03-08 03:26 UTC, mikayla-maki commented
Don't worry at all! Now you know, and can make even better PRs next time :D :D :D

2024-03-08 04:16 UTC, merged