Show status of "Find References"
zed-industries/zed pull request #9818
Opened 2024-03-26 15:49 UTC by danielzsh

Fixes #4380

Release Notes:

- Adds a status indicator for "Find References"

2024-03-27 00:30 UTC, TerminalFi commented
@danielzsh LEO request and response contain a unique ID. this is generally how the LSP client can track a response to a request

2024-03-27 00:37 UTC, TerminalFi commented
For point 3

you’ll probably have to do a query for what is under the cursor in the active buffer to get what is being queried since the actual LSP request only contains Position information of where the cursor is at time of request

2024-03-27 01:19 UTC, danielzsh commented
> @danielzsh LEO request and response contain a unique ID. this is generally how the LSP client can track a response to a request

Do you know where I can get that unique ID? I can't find it anywhere in the codebase 😰

2024-03-27 01:23 UTC, TerminalFi commented
> > @danielzsh LEO request and response contain a unique ID. this is generally how the LSP client can track a response to a request
> 
> 
> 
> Do you know where I can get that unique ID? I can't find it anywhere in the codebase 😰 

lsp.rs:122

2024-03-27 01:32 UTC, TerminalFi commented
I think that would then create 2 places that ids would have to be managed and might not be the ideal approach. But will let a Zed dev provide feedback. 

Ideally you'll expose it from the language server. Since it is already associated with a buffer.

2024-03-27 01:55 UTC, mikayla-maki commented
I recently attempted a version of this and hit the same problem. I think it would be best to expose the ID :)

2024-03-27 03:38 UTC, danielzsh commented
By the way, do you have any idea why the macos tests are taking such an absurd amount of time?
<img width="823" alt="image" src="https://github.com/zed-industries/zed/assets/65467530/fa3d56b5-b7c5-4b77-850b-9751a8222b6f">

2024-03-27 06:08 UTC, danielzsh commented
> you’ll probably have to do a query for what is under the cursor in the active buffer to get what is being queried since the actual LSP request only contains Position information of where the cursor is at time of request

Any idea if there's an easy way to get the whole symbol based on just the cursor position?

2024-03-30 00:05 UTC, mikayla-maki commented
I wouldn't worry about finding the name of the symbol you're hovering, leave that for a follow up PR :)

2024-03-30 05:19 UTC, danielzsh commented
<img width="307" alt="image" src="https://github.com/zed-industries/zed/assets/65467530/47e7a735-1fff-4a4b-907b-1d011781ba6b">

Here's how the message looks in its current state; it would be nice to keep a live updating count of the references that have been found, but I'm not sure how to do that (as mentioned in point 4 above).

There's also a short gap between the time the 'finding references...' status is cleared and when the references window is actually opened, since the code is currently written like so:
```rs
if status.is_some() {
  cx.update(|cx| {
      this.update(cx, |this, cx| {
          this.on_lsp_work_end(
              language_server.server_id(),
              id.to_string(),
              cx,
          );
      })
  })
  .log_err();
}
// ....
request
  .response_from_lsp(
      response,
      this.upgrade().ok_or_else(|| anyhow!("no app context"))?,
      buffer_handle,
      language_server.server_id(),
      cx,
  )
  .await
```
`cx` is moved into `response_from_lsp` so I can't move the `cx.update(...` after it. I could move the `on_lsp_work_end` logic into `response_from_lsp` directly, but this causes us to lose the generality the current approach offers (which is if we want to display the status for some LSP command, we simply need to override its `status` function). Any thoughts/suggestions?

2024-04-04 17:06 UTC, mikayla-maki commented on crates/lsp/src/lsp.rs
> +    pub fn next_id(&self) -> &AtomicI32 {
This should just return an i32

2024-04-04 18:45 UTC, mikayla-maki requested changes
Looks pretty good! Let's fix that ID API and see where we get to :)

2024-04-04 18:45 UTC, mikayla-maki commented on crates/project/src/project.rs
> +                    let id = language_server.next_id().load(SeqCst);
I think this approach of grabbing the next ID seems error prone. An alternative design could be that we create a custom struct that implements `Future`, that gets returned from `language_server.request()`, that also stores the ID on itself. That way we can re-arrange this logic such that we call `language_server.request()`, get the ID off of it, and then await it after we've put in the language server progress.

2024-04-06 01:59 UTC, danielzsh commented
I implemented a `FutureWithId` struct that contains an id in addition to wrapping a future and everything still works as before, but the implementation might need a bit more polishing? New to Rust, so I'm not too sure what's going on with all the Boxes and Pins 😓

2024-04-07 02:32 UTC, mikayla-maki commented
Good attempt! However I had an idea for a way to do it without involving a `Box<>`, and in the process of explaining it I realized it would probably be easier to push the refactor myself :D

2024-04-07 02:48 UTC, mikayla-maki approved these changes

2024-04-07 02:48 UTC, merged

2024-04-07 02:48 UTC, mikayla-maki commented
Thank you!

2024-04-08 05:22 UTC, danielzsh commented
By the way, do you have any idea how we can implement either:
- Showing the actual symbol name in the status, e.g. `Finding references to AppContext` (would this perhaps require an LSP request to get the symbol name first?)
- Showing progress updates, e.g. `Found 100 references... -> Found 101 references...`